name: Deploy to Test
on:
  push:
    branches:
      - Testing

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://aspiredigital.asuscomm.com:8085/api/deploy'
        method: 'GET'
        data: '{"batpath": "C:/Users/Administrator/Desktop/ad-application/deploy.bat"}'
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
