
on:
  push:
    branches:
      - Testing

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Deploy to Testing Environment
      uses: fjogeleit/http-request-action@v1
      with:
        url: http://aspiredigital.asuscomm.com:8085/api/deploy?batpath=C:/Users/Administrator/Desktop/ad-application/deploy.bat
        Method: GET
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
